# Generated by Django 4.2 on 2023-04-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
