# Generated by Django 4.2 on 2023-04-20 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("community", "0002_remove_book_author_delete_author_book_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="borrow_date",
        ),
        migrations.RemoveField(
            model_name="book",
            name="borrower",
        ),
        migrations.RemoveField(
            model_name="book",
            name="manager",
        ),
        migrations.CreateModel(
            name="Borrow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("borrower", models.CharField(max_length=10)),
                ("borrow_date", models.DateTimeField()),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="community.book"
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        max_length=10,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
