# Generated by Django 4.2 on 2023-05-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0004_alter_borrow_book_alter_borrow_borrow_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrow",
            name="state",
            field=models.BooleanField(default=False),
        ),
    ]
