# Generated by Django 4.2 on 2023-05-16 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("community", "0005_borrow_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrow",
            name="borrow_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="borrow",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                max_length=10,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="borrow",
            name="state",
            field=models.BooleanField(default=True),
        ),
    ]
